server:
  servlet:
    context-path: /v1/notes-service

spring:
  profiles:
     active: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      auto-ddl: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/t_my_notes
    username: ${db_user}
    password: ${db_password}

twilio:
  account-sid: ${TWILIO_ACOUNT_SID}
  api-key: ${TWILIO_API_KEY}

alerts:
  to-phone-number: ${RECIPIENT_PHONE_NUMBER}
  from-phone-number: ${SENDER_PHONE_NUMBER}